version: "3.8"

services:

  #Nginx Service
  webserver:
    image: nginx:stable-alpine
    container_name: lcp_nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes: 
      - .:/var/www/html
      - ./dockerize/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on: 
      - php
    networks:
      - laraveldockerize

  #PHP Service
  php:
    build:
      context: .
      dockerfile: ./dockerize/app/php.dockerfile
    container_name: lcp_php
    volumes: 
      - .:/var/www/html
    ports: 
      - "9000:9000"
    networks:
      - laraveldockerize 

  #Composer Service
  composer:
    image: composer:latest
    container_name: lcp_composer
    volumes: 
      - .:/var/www/html
    working_dir: /var/www/html
    depends_on: 
      - php
    networks:
      - laraveldockerize    

  #NPM Service
  npm:
    image: node:14.9
    container_name: lcp_npm
    volumes: 
      - .:/var/www/html
    working_dir: /var/www/html
    entrypoint: ['npm']

  #Artisan Service
  artisan:
    build: 
      context: .
      dockerfile: ./dockerize/app/php.dockerfile
    container_name: lcp_artisan
    volumes: 
      - .:/var/www/html
    working_dir: /var/www/html
    entrypoint: ['php', '/var/www/html/artisan']
    networks:
      - laraveldockerize


#Docker Networks
networks:
  laraveldockerize: